### ISSUE TITLE
License violation notification

### ISSUE THREAD

**Issue by secit-pl** [DaDeather/symfony-imap-bundle#1]
Dear repository owner. As your source code is a copy of my MIT licensed code (https://github.com/secit-pl/imap-bundle) I want to warn you that your current license violates the original bundle license. Please update the license as soon as possible.

For additional info where is the problem check this stackexchange answer https://opensource.stackexchange.com/questions/8853/can-i-change-the-copyright-holder-name-and-year-of-an-mit-license

**Comment by DaDeather** [comment]
There you go :-). You know it would be great to put more effort into maintaining the bundle instead of these kind of things.
That would have made this bundle here totally unnecessary.
